name: Build Kivy App APK

on: push: branches: [ main ]

jobs: build: runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'

- name: Install dependencies
  run: |
    sudo apt update
    sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
    python3 -m pip install --upgrade pip
    pip install buildozer cython kivy requests

- name: Accept licenses and install SDK tools
  run: |
    mkdir -p ~/.android && touch ~/.android/repositories.cfg
    yes | sdkmanager --licenses || true
    yes | sdkmanager "platforms;android-30" "build-tools;30.0.3"
  env:
    ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk

- name: Build APK
  run: |
    buildozer android debug

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: kivy-app-apk
    path: bin/*.apk

