name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_BUILD_TOOLS_VERSION: "30.0.3"

    steps:
    - name: Clean Android SDK cache
      run: rm -rf $HOME/.buildozer/android/platform

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip wget
        pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Download Android SDK cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        rm cmdline-tools.zip
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk

    - name: Accept licenses and install required SDK packages
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk

    - name: Download and setup Android NDK 25b
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d $HOME
        rm android-ndk-r25b-linux.zip

    - name: Set environment variables for buildozer
      run: |
        echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/android-ndk-r25b" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: buildozer android debug
